var str1 = "string";
console.log(str1, typeof (str1));
var str2 = new String("str2");
console.log(str2, typeof (str2));
console.log(str2 + "kasra");
var LongString1 = "   Kasra, Hosseini,    Web Developer   "
console.log(LongString1.length);
console.log(LongString1.charAt(7));
console.log(LongString1.charCodeAt(1));
var FirstName = "Kasra";
var LastNAme = "Hosseini";
console.log(FirstName.concat(" ", LastNAme));
console.log(LongString1.includes("kasra"));
console.log(LongString1.search("i"));
console.log(LongString1.indexOf("ksara", 7));
console.log(LongString1.startsWith("K", 7));
console.log(LongString1.endsWith("r"));
console.log(FirstName.padEnd(10, "!"));
console.log(FirstName.padStart(10, "!"));
console.log(FirstName.repeat(10));
console.log(LongString1.replace("Kasra", "Aida"));
console.log(LongString1.slice(17, 21));
console.log(LongString1.substring(21, 17));
console.log(LongString1.split(", "));
console.log(LongString1.toLowerCase());
console.log(LongString1.toUpperCase());
console.log(LongString1.trim());
console.log(LongString1.trimStart());
console.log(LongString1.trimEnd());
console.log(LongString1.match(/[A - Z]/g));
// console.log(LongString1.matchAll(/[A - Z]/g));